/* =============================================================
 *  da7212_speaker_init.c
 *  – fully revised register sequence (PLL INT/FRAC, mixer, OE, etc.)
 * =============================================================*/

#include "da7212_speaker_init.h"
#include "r_iic_master.h"
#include "common_utils.h"      /* APP_ERR_PRINT, APP_ERR_TRAP */
#include "hal_data.h"          /* g_i2c_master0_ctrl, cfg, delays */

/* External I²C master instance (generated by FSP) */
extern iic_master_instance_ctrl_t g_i2c_master0_ctrl;
extern const i2c_master_cfg_t     g_i2c_master0_cfg;

/* -------------------------------------------------------------
 *  Local helper – single‑byte I²C write (blocking)
 * -----------------------------------------------------------*/
static inline fsp_err_t da7212_write(uint8_t addr, uint8_t data)
{
    uint8_t buf[2] = { addr, data };
    return R_IIC_MASTER_Write(&g_i2c_master0_ctrl, buf, 2, false);
}

/* -------------------------------------------------------------
 *  Wait until System Controller busy flags clear (BUSY == 0)
 * -----------------------------------------------------------*/
static fsp_err_t da7212_wait_ready(void)
{
    uint8_t status;
    do
    {
        fsp_err_t err = R_IIC_MASTER_Read(&g_i2c_master0_ctrl, &status, 1, true /* restart */);
        if (FSP_SUCCESS != err) return err;
    } while (status & 0x30);   /* SC1_BUSY|SC2_BUSY */
    return FSP_SUCCESS;
}

/* -------------------------------------------------------------
 *  Public API
 * -----------------------------------------------------------*/
fsp_err_t da7212_speaker_init(void)
{
    fsp_err_t err;

    /* 1) Open I²C bus */
    err = R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("DA7212: I2C open failed (0x%02X)\r\n", err);
        return err;
    }

    /* 2) Exit standby – SYSTEM_ACTIVE */
    err = da7212_write(0xFD, 0x01);   if (FSP_SUCCESS != err) return err;
    R_BSP_SoftwareDelay(40, BSP_DELAY_UNITS_MILLISECONDS);

    /* 3) Enable master bias */
    err = da7212_write(0x23, 0x08);   if (FSP_SUCCESS != err) return err;
    R_BSP_SoftwareDelay(25, BSP_DELAY_UNITS_MILLISECONDS);

    /* 4) Sample rate = 48 kHz (SR = 0x0B) */
    err = da7212_write(0x22, 0x0B);   if (FSP_SUCCESS != err) return err;

    /* 5) PLL configuration – 12.288 MHz MCLK → 98.304 MHz SYSCLK */
    const uint8_t pll_seq[][2] = {
        {0x24, 0x00},          /* PLL FRAC MSB */
        {0x25, 0x00},          /* PLL FRAC LSB */
        {0x26, 0x20},          /* PLL INT = 0x20 (32) */
        {0x27, 0x84}           /* PLL_EN | PLL_SRM_EN | INDIV=10 */
    };
    for (size_t i = 0; i < sizeof(pll_seq)/2; ++i)
    {
        err = da7212_write(pll_seq[i][0], pll_seq[i][1]);
        if (FSP_SUCCESS != err) return err;
    }

    /* 6) DAI Clock Mode – MCU master, 256×MCLK, BCLK output */
    err = da7212_write(0x28, 0x81);   if (FSP_SUCCESS != err) return err;

    /* 7) DAI Control – I²S, 16‑bit, DAI_EN */
    err = da7212_write(0x29, 0x88);   if (FSP_SUCCESS != err) return err;

    /* 8) DAC routing – DAC_L/R ← DAI_L/R */
    err = da7212_write(0x2A, 0x32);   if (FSP_SUCCESS != err) return err;

    /* 9) Charge pump enable (for mixer out) */
    err = da7212_write(0x47, 0xA1);   if (FSP_SUCCESS != err) return err;

    /* 10) Mixer: DAC_L/R → MIXOUT_L/R enable */
    err = da7212_write(0x4B, 0x08);   if (FSP_SUCCESS != err) return err; /* MIXIN_L_TO_MIXOUT_L */
    err = da7212_write(0x4C, 0x08);   if (FSP_SUCCESS != err) return err; /* MIXIN_R_TO_MIXOUT_R */

    /* 11) Amplifier gain = 0 dB (0x30) */
    err = da7212_write(0x4A, 0x30);   if (FSP_SUCCESS != err) return err;

    /* 12) Line amplifier enable + Output enable */
    err = da7212_write(0x6D, 0x88);   if (FSP_SUCCESS != err) return err;

    /* 13) Mixout amplifiers enable */
    err = da7212_write(0x6E, 0x81);   if (FSP_SUCCESS != err) return err;
    err = da7212_write(0x6F, 0x81);   if (FSP_SUCCESS != err) return err;

    /* 14) Apply system controller sequence (MODE_SUBMIT, gain ramp) */
    err = da7212_write(0x51, 0xD9);   if (FSP_SUCCESS != err) return err;

    /* 15) Wait until internal power‑up complete */
    err = da7212_wait_ready();        if (FSP_SUCCESS != err) return err;
    R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);

    /* 16) Close I²C – release bus for other devices */
    (void) R_IIC_MASTER_Close(&g_i2c_master0_ctrl);

    return FSP_SUCCESS;
}
